version: '3.8'
services:
  server:
    build: .
    volumes:
      - .:/app
    ports:
      - "127.0.0.1:8000:8000"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx:/etc/nginx/conf.d
    ports:
      - "127.0.0.1:80:80"
    depends_on:
      - server